# Generated by Django 5.2.1 on 2025-05-12 21:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
