# Generated by Django 5.2.1 on 2025-05-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_type_recruitment_salary_recruitment_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
