# Generated by Django 5.2.1 on 2025-05-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_recruitment_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='types',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='salary',
        ),
        migrations.AddField(
            model_name='new',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
