# Generated by Django 5.2.1 on 2025-05-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_recruitment_types_remove_recruitment_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='salary',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
