# Generated by Django 5.2.1 on 2025-05-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_remove_new_salary_recruitment_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
